tests/old.o: tests/new.c tests/new.h
	echo compiling old
	echo compiling again

tests/old.o: tests/new.c tests/new.h
	echo compiling old2
	echo compiling again2

tests/new.o: tests/old.c tests/old.h
	echo compiling new